export const TechTeam = [
  { name: "NAIRIT" },
  { name: "SHOURYA" },
  { name: "KUSHAL" },
  { name: "ANSH" },
  { name: "PRASHANT" },
  { name: "GIRIK" },
  { name: "RAJDEEP" },
  { name: "KAPIL" },
  { name: "ABHINAY" },
  { name: "PREM" },
  { name: "SHIVANSH" },
  { name: "AJEET" },
  { name: "TUSHAR" },
  { name: "AKASH" },
  { name: "NANCY" },
  { name: "HARSH" },
  { name: "SHIVANGI" },
  { name: "HARMANJEET" },
];

export const NonTechTeam = [
  { name: "KARTIKEY" },
  { name: "PRIYANSHU" },
  { name: "SARTHAK" },
  { name: "ADI" },
  { name: "NAVYA" },
  { name: "ADITYA" },
  { name: "SUMIT" },
  { name: "ALOK" },
  { name: "DISHA" },
  { name: "AYUSHMAN" },
  { name: "PALAK" },
];
